name: Android Pull Request

# Trigger conditions (build only on pull_request for main branch)
on:
  pull_request:
    branches:
      - main

env:
  working-directory: .
  android-api-level: 34

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      PUBLISH_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      JITPACK_AUTH_TOKEN: ${{ secrets.JITPACK_AUTH_TOKEN }}


    steps:
      - uses: actions/checkout@v4

      # Set up Eclipse Temurin Java 17
      - name: Set up Eclipse Temurin Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.13
        with:
          cmake-version: '3.25.1'
      - run: cmake --version
      - run: |
          sudo apt-get update
          sudo apt-get install ninja-build
          ninja --version
      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Gradlew Build
        working-directory: ${{env.working-directory}}
        run: ./gradlew clean build

      - name: Gradlew Test
        working-directory: ${{env.working-directory}}
        run: ./gradlew test --stacktrace

#      # Set a new version depending on source branch and build number (can't overwrite existing versions)
#      - name: Set git reference of pull request as version string
#        if: github.event_name == 'pull_request'
#        run: |
#          echo "VERSION_STRING=${GITHUB_HEAD_REF##*/}.${{ github.run_number }}" >> $GITHUB_ENV
#
#      - name: Publish AAR to GitHub Packages
#        working-directory: ${{env.working-directory}}
#        run: ./gradlew publish
